openapi: 3.0.0
info:
  title: 10-E-commerce
  version: 1.0.0
servers:
  - url: https://e-commerce-swagger.onrender.com
tags:
  - name: auth
  - name: user
  - name: product
  - name: Review
  - name: Order
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # Optional, indicates the token type
      description: The Token values do not need " "
paths:
  /api/v1/auth/login:
    post:
      tags:
        - auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: peter@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/register:
    post:
      tags:
        - auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: peter
                email: peter@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/logout:
    get:
      tags:
        - auth
      summary: Logout User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/users:
    get:
      tags:
        - user
      summary: Get All Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/{id}:
    get:
      tags:
        - user
      summary: Get Single User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/showMe:
    get:
      tags:
        - user
      summary: Show Current User
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/updateUser:
    patch:
      tags:
        - user
      summary: Update User
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: susanUpdated
                email: susan@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/updateUserPassword:
    patch:
      tags:
        - user
      summary: Update User Password
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                oldPassword: newSecret
                newPassword: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/products:
    get:
      tags:
        - product
      summary: Get All Products
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - product
      summary: Create Product
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: testing
                price: 25999
                colors:
                  - "#ff0000"
                  - "#00ff00"
                  - "#0000ff"
                company: marcos
                description: a big black box
                category: office
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/products/{id}:
    get:
      tags:
        - product
      summary: Get Single Product
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - product
      summary: Update Product
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: updated product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - product
      summary: Delete Product
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/products/uploadImage:
    post:
      tags:
        - product
      summary: Upload Image
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/products/{id}/reviews:
    get:
      tags:
        - product
      summary: Get Single Product Review
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/reviews:
    get:
      tags:
        - Review
      summary: Get All Review
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Review
      summary: Create Review
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product: "123"
                rating: "1"
                title: bad product
                comment: very, very bad product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/reviews/{id}:
    get:
      tags:
        - Review
      summary: Get Single Review
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Review
      summary: Update Review
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                product: "123"
                rating: "5"
                title: bad product
                comment: very, very bad product
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Review
      summary: Delete Review
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/orders:
    get:
      tags:
        - Order
      summary: Get All Orders
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Order
      summary: Create Order
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tax: 499
                shippingFee: 799
                items:
                  - name: bed
                    price: 2699
                    image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
                    amount: 3
                    product: 66b8d3e83079cde84db9a6c6
                  - name: chair
                    price: 2999
                    image: https://dl.airtable.com/.attachmentThumbnails/e8bc3791196535af65f40e36993b9e1f/438bd160
                    amount: 2
                    product: 66cb135626e150f398e09b78
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/orders/{id}:
    get:
      tags:
        - Order
      summary: Get Single Order
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Order
      summary: Update Order
      parameters:
        - in: path
          name: id
          required: true
          description: Id required
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                paymentIntentId: someRandomId
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/orders/showAllMyOrders:
    get:
      tags:
        - Order
      summary: Show Current User Orders
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
